config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :users
  resources :categories
  root 'articles#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :article
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :category

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_presence_of :category
  validates_presence_of :title

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(' ')
  end

  def tag_list=(tags_string)
    tags_names = tags_string.split(',').collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tags_names.collect{ |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params.has_key?(:category_id)
      @articles = Category.find(params[:category_id]).articles
    else
      @articles = Article.all
    end
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = @article.comments.new
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # GET /articles/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article  = Article.new(article_params)
    @view     = 'index'

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
        format.js { render 'shared/ajax_body.js' }
      else
        @view = 'new'
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
        format.js { render 'shared/ajax_body.js' }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @view     = 'show'
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
        format.js { render 'shared/ajax_body.js' }
      else
        @view = 'edit'
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
        format.js { render 'shared/ajax_body.js' }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :tag_list, :image, :category_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    redirect_to article_path(@comment.article)
  end

  private
    def comment_params
      params.require(:comment).permit(:author, :body)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    respond_to do |format|
      format.html {render :index}
      format.js { render 'shared/ajax_body.js' }
    end
  end
  def show
    @tag = Tag.find(params[:id])
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html {render :index}
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # GET /users/new
  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js { render 'shared/ajax_body.js' }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: "panel panel-danger") do
        concat(content_tag(:div, class: "panel-heading") do
          concat(content_tag(:h4, class: "panel-title") do
            concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: "panel-body") do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article, layout: :horizontal, label_col: "col-sx-4 col-sm-1", control_col: "col-xs-8 col-sm-11", :remote => true) do |f| %>
  	<%= errors_for(@article) %>
    <%= f.text_field :title, class: "col-xs-4 col-md-8" %>
    <% category_array = Category.all.collect { |cat| [cat.name, cat.id] } %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: 'Select category'}, class: "select2" %>
    <%= f.text_area :body, class: "wysihtml5" %>
    <%= f.text_field :tag_list, class: "col-xs-4 col-md-8" %>
    <%= f.file_field :image, class: "col-xs-4 col-md-8" %>
    <hr/>
    <div class="pull-right">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
    <%= link_to 'Back', articles_path, role: "button", class: "btn btn-info", :remote => true %>
<% end %>

app/views/articles/edit.html.erb
<h1 class="page-header">Editing Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article, role: "button", class: "btn btn-default", :remote => true %></td>
        <td><%= link_to 'Edit', edit_article_path(article), role: "button", class: "btn btn-primary", :remote => true %></td>
        <td><%= link_to 'Destroy', article, method: :delete, role: "button", class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Article', new_article_path, role: "button", class: "btn btn-success", :remote => true %>

<br>

app/views/articles/new.html.erb
<h1 class="page-header">New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="page-header">
  Show Article
  <%= link_to 'Edit', edit_article_path(@article), role: "button", class: "btn btn-primary", :remote => true %>
</h1>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-2 col-sm-2 col-md-1">
    <strong>Title:</strong>
  </div>
  <div class="col-xs-10 col-sm-10 col-md-11">
    <p class="lead">
      <%= @article.title %>
    </p>
  </div>
  <div class="col-xs-2 col-sm-2 col-md-1">
    <strong>Category:</strong>
  </div>
  <div class="col-xs-10 col-sm-10 col-md-11">
    <p class="lead">
      <% if defined?(@article.category.name) %>
        <%= @article.category.name %>
      <% else %>
        No category
      <% end %>
    </p>
  </div>
  <div class="col-xs-2 col-sm-2 col-md-1">
    <strong>Body:</strong>
    <div class="col-xs-10 col-sm-10 col-md-11">
      <p class="lead">
        <%= @article.body.html_safe %>
      </p>
    </div>
  </div>
  <div class="col-xs-2 col-sm-2 col-md-1">
    <strong>Body:</strong>
    <div class="col-xs-10 col-sm-10 col-md-11">
      <p class="lead">
        <%= @article.image_file_name %>
        <%= image_tag @article.image.url %>
      </p>
    </div>
  </div>
</div>
<div class="row">
  <h1>Add a comment</h1>
  <%= bootstrap_form_for([@article, @comment],  layout: :horizontal, label_col: "col-sx-4 col-sm-1", control_col: "col-xs-8 col-sm-11") do |f| %>
    <%= f.text_field :author, class: "col-xs-4 col-md-8" %>
    <%= f.text_area :body, class: "wysihtml5" %>
    <%= f.submit %>
  <% end %>
  <h1>Comments</h1>
  <ul>
    <% @article.comments.each do |comment| %>
      <li><%= comment.author %> : <%= comment.body %></li>
    <% end %>
  </ul>
</div>
<h3>Tags</h3>
<ul>
<% @article.tags.each do |tag| %>
  <li><%= tag.name %></li>
<% end %>
</ul>
<hr/>
<div class="row">
  <%= link_to 'Back', articles_path, role: "button", class: "btn btn-info", :remote => true %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My test</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'shared/navigation_bar' %>
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->
    <div class="container-fluid main">
    	<div class="row">
        <nav class="col-xs-2 menu">
          <ul class="nav-sidebar">
            <li class="withoutripple">
              <%= link_to 'All', articles_path, class: 'sidebar-menu', :remote => true %>
            </li>
            <% categories = Category.all %>
            <% categories.each do |category| %>
              <li class="withoutripple">
                <%= link_to category.name, articles_path(:category_id => category.id), class: 'sidebar-menu', :remote => true %>
              </li>
            <% end %>
            <li class="withoutripple <% if current_page?(controller: 'tags') %>active<% end %>">
              <%= link_to 'Tags', tags_path, class: 'sidebar-menu', :remote => true %>
            </li>
            <li class="withoutripple <% if current_page?(controller: 'users') %>active<% end %>">
              <%= link_to 'Users', users_path, class: 'sidebar-menu', :remote => true %>
            </li>
          </ul>
        </nav>
        <div class="col-xs-10">
          <div class="well" id="body_page">
            <%= yield %>
          </div>
        </div>
      </div>
	 </div>
   <div id="complete-dialog" class="modal fade" tabindex="-1">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
           <h4 class="modal-title">Dialog</h4>
         </div>
         <div class="modal-body">
           <p></p>
         </div>
         <div class="modal-footer">
           <button class="btn btn-primary" data-dismiss="modal">Dismiss</button>
         </div>
       </div>
     </div>
  </div>
  </body>
</html>

app/views/shared/_navigation_bar.html.erb
<div class="navbar navbar-warning">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="javascript:void(0)">Brand</a>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
        <ul class="nav navbar-nav">
            <li class="active"><a href="javascript:void(0)">Active</a></li>
            <li><a href="javascript:void(0)">Link</a></li>
            <li class="dropdown">
                <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0)">Action</a></li>
                    <li><a href="javascript:void(0)">Another action</a></li>
                    <li><a href="javascript:void(0)">Something else here</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Dropdown header</li>
                    <li><a href="javascript:void(0)">Separated link</a></li>
                    <li><a href="javascript:void(0)">One more separated link</a></li>
                </ul>
            </li>
        </ul>
        <form class="navbar-form navbar-left">
            <input type="text" class="form-control col-lg-8" placeholder="Search">
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:void(0)">Link</a></li>
            <li class="dropdown">
                <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0)">Action</a></li>
                    <li><a href="javascript:void(0)">Another action</a></li>
                    <li><a href="javascript:void(0)">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="javascript:void(0)">Separated link</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

app/views/shared/ajax_body.js.erb
<% if defined?(@view) %>
  <% @view_path = controller.controller_name + '/' + @view %>
<% else %>
  <% @view_path = controller.controller_name + '/' + controller.action_name %>
<% end %>

$('#body_page').addClass('animated fadeOutDown')
$('#body_page').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationed animationned', function() {
  $('#body_page').html("<%= escape_javascript(render file: @view_path , locals: { articles: @articles } ) %>")
  $('#body_page').removeClass('animated fadeOutDown')
  $('#body_page').addClass('animated fadeInUp')
  $("#body_page .wysihtml5").wysihtml5()
  $("#body_page .select2").select2()
});

app/views/shared/index.js.erb
$('#body_page').addClass('animated fadeOutDown')
$('#body_page').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationed animationned', function() {
  $('#body_page').html("<%= escape_javascript(render partial: 'index', locals: { articles: @articles } ) %>")
  $('#body_page').removeClass('animated fadeOutDown')
  $('#body_page').addClass('animated fadeInUp');
});

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Tags</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag, role: "button", class: "btn btn-default", :remote => true %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag), role: "button", class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, role: "button", class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/show.html.erb
<h1 class="page-header">
  Show Tag
</h1>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-2 col-sm-2 col-md-1">
    <strong>Name:</strong>
  </div>
  <div class="col-xs-10 col-sm-10 col-md-11">
    <p class="lead">
      <%= @tag.name %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-xs-2 col-sm-2 col-md-1">
    Articles list
  </div>
  <div class="col-xs-10 col-sm-10 col-md-11">
    <div class="list-group">
      <% @tag.articles.each do |article| %>
        <%= link_to article.title, article, class: 'list-group-item' %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <%= link_to 'Back', tags_path, role: "button", class: "btn btn-info" %>
</div>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sx-4 col-sm-1", control_col: "col-xs-8 col-sm-11") do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :username, class: "col-xs-4 col-md-8" %>
  </div>
  <div class="field">
    <%= f.text_field :email, class: "col-xs-4 col-md-8" %>
  </div>
  <div class="field">
    <%= f.password_field :password, class: "col-xs-4 col-md-8"  %>
  </div>
    <%= f.password_field :password_confirmation, class: "col-xs-4 col-md-8"  %>
  <div class="field">
  </div>
  <div class="pull-right">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
  <%= link_to 'Back', users_path, role: "button", class: "btn btn-info" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, role: "button", class: "btn btn-default", remote: true %></td>
        <td><%= link_to 'Edit', edit_user_path(user), role: "button", class: "btn btn-primary", remote: true %></td>
        <td><%= link_to 'Destroy', user, method: :delete, role: "button", class: "btn btn-danger", data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, role: "button", class: "btn btn-success", remote: true %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path, role: "button", class: "btn btn-info" %>